// text_service.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: src/protobuf/plot.proto

package plot

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TextService_ProcessText_FullMethodName       = "/plot.TextService/ProcessText"
	TextService_StreamProcessText_FullMethodName = "/plot.TextService/StreamProcessText"
	TextService_AnalyzeTextStream_FullMethodName = "/plot.TextService/AnalyzeTextStream"
	TextService_ChatStream_FullMethodName        = "/plot.TextService/ChatStream"
)

// TextServiceClient is the client API for TextService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Сервис с методами
type TextServiceClient interface {
	// Обычный RPC (запрос-ответ)
	ProcessText(ctx context.Context, in *TextRequest, opts ...grpc.CallOption) (*TextResponse, error)
	// Server Streaming (сервер отправляет несколько сообщений)
	StreamProcessText(ctx context.Context, in *TextRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TextChunk], error)
	// Client Streaming (клиент отправляет несколько сообщений)
	AnalyzeTextStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[TextChunk, TextAnalysis], error)
	// Bidirectional Streaming (оба направления)
	ChatStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ChatMessage, ChatMessage], error)
}

type textServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTextServiceClient(cc grpc.ClientConnInterface) TextServiceClient {
	return &textServiceClient{cc}
}

func (c *textServiceClient) ProcessText(ctx context.Context, in *TextRequest, opts ...grpc.CallOption) (*TextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TextResponse)
	err := c.cc.Invoke(ctx, TextService_ProcessText_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *textServiceClient) StreamProcessText(ctx context.Context, in *TextRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TextChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TextService_ServiceDesc.Streams[0], TextService_StreamProcessText_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TextRequest, TextChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TextService_StreamProcessTextClient = grpc.ServerStreamingClient[TextChunk]

func (c *textServiceClient) AnalyzeTextStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[TextChunk, TextAnalysis], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TextService_ServiceDesc.Streams[1], TextService_AnalyzeTextStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TextChunk, TextAnalysis]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TextService_AnalyzeTextStreamClient = grpc.ClientStreamingClient[TextChunk, TextAnalysis]

func (c *textServiceClient) ChatStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ChatMessage, ChatMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TextService_ServiceDesc.Streams[2], TextService_ChatStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChatMessage, ChatMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TextService_ChatStreamClient = grpc.BidiStreamingClient[ChatMessage, ChatMessage]

// TextServiceServer is the server API for TextService service.
// All implementations must embed UnimplementedTextServiceServer
// for forward compatibility.
//
// Сервис с методами
type TextServiceServer interface {
	// Обычный RPC (запрос-ответ)
	ProcessText(context.Context, *TextRequest) (*TextResponse, error)
	// Server Streaming (сервер отправляет несколько сообщений)
	StreamProcessText(*TextRequest, grpc.ServerStreamingServer[TextChunk]) error
	// Client Streaming (клиент отправляет несколько сообщений)
	AnalyzeTextStream(grpc.ClientStreamingServer[TextChunk, TextAnalysis]) error
	// Bidirectional Streaming (оба направления)
	ChatStream(grpc.BidiStreamingServer[ChatMessage, ChatMessage]) error
	mustEmbedUnimplementedTextServiceServer()
}

// UnimplementedTextServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTextServiceServer struct{}

func (UnimplementedTextServiceServer) ProcessText(context.Context, *TextRequest) (*TextResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProcessText not implemented")
}
func (UnimplementedTextServiceServer) StreamProcessText(*TextRequest, grpc.ServerStreamingServer[TextChunk]) error {
	return status.Error(codes.Unimplemented, "method StreamProcessText not implemented")
}
func (UnimplementedTextServiceServer) AnalyzeTextStream(grpc.ClientStreamingServer[TextChunk, TextAnalysis]) error {
	return status.Error(codes.Unimplemented, "method AnalyzeTextStream not implemented")
}
func (UnimplementedTextServiceServer) ChatStream(grpc.BidiStreamingServer[ChatMessage, ChatMessage]) error {
	return status.Error(codes.Unimplemented, "method ChatStream not implemented")
}
func (UnimplementedTextServiceServer) mustEmbedUnimplementedTextServiceServer() {}
func (UnimplementedTextServiceServer) testEmbeddedByValue()                     {}

// UnsafeTextServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TextServiceServer will
// result in compilation errors.
type UnsafeTextServiceServer interface {
	mustEmbedUnimplementedTextServiceServer()
}

func RegisterTextServiceServer(s grpc.ServiceRegistrar, srv TextServiceServer) {
	// If the following call panics, it indicates UnimplementedTextServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TextService_ServiceDesc, srv)
}

func _TextService_ProcessText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TextServiceServer).ProcessText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TextService_ProcessText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TextServiceServer).ProcessText(ctx, req.(*TextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TextService_StreamProcessText_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TextRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TextServiceServer).StreamProcessText(m, &grpc.GenericServerStream[TextRequest, TextChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TextService_StreamProcessTextServer = grpc.ServerStreamingServer[TextChunk]

func _TextService_AnalyzeTextStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TextServiceServer).AnalyzeTextStream(&grpc.GenericServerStream[TextChunk, TextAnalysis]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TextService_AnalyzeTextStreamServer = grpc.ClientStreamingServer[TextChunk, TextAnalysis]

func _TextService_ChatStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TextServiceServer).ChatStream(&grpc.GenericServerStream[ChatMessage, ChatMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TextService_ChatStreamServer = grpc.BidiStreamingServer[ChatMessage, ChatMessage]

// TextService_ServiceDesc is the grpc.ServiceDesc for TextService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TextService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "plot.TextService",
	HandlerType: (*TextServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessText",
			Handler:    _TextService_ProcessText_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamProcessText",
			Handler:       _TextService_StreamProcessText_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "AnalyzeTextStream",
			Handler:       _TextService_AnalyzeTextStream_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "ChatStream",
			Handler:       _TextService_ChatStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "src/protobuf/plot.proto",
}
