# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from src.protobuf import plot_pb2 as src_dot_protobuf_dot_plot__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in src/protobuf/plot_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TextServiceStub:
    """Сервис с методами
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessText = channel.unary_unary(
                '/plot.TextService/ProcessText',
                request_serializer=src_dot_protobuf_dot_plot__pb2.TextRequest.SerializeToString,
                response_deserializer=src_dot_protobuf_dot_plot__pb2.TextResponse.FromString,
                _registered_method=True)


class TextServiceServicer:
    """Сервис с методами
    """

    def ProcessText(self, request, context):
        """Обычный RPC (запрос-ответ)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TextServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessText': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessText,
                    request_deserializer=src_dot_protobuf_dot_plot__pb2.TextRequest.FromString,
                    response_serializer=src_dot_protobuf_dot_plot__pb2.TextResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'plot.TextService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('plot.TextService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TextService:
    """Сервис с методами
    """

    @staticmethod
    def ProcessText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/plot.TextService/ProcessText',
            src_dot_protobuf_dot_plot__pb2.TextRequest.SerializeToString,
            src_dot_protobuf_dot_plot__pb2.TextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class PlotServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GeneratePlot = channel.unary_unary(
                '/plot.PlotService/GeneratePlot',
                request_serializer=src_dot_protobuf_dot_plot__pb2.PlotRequest.SerializeToString,
                response_deserializer=src_dot_protobuf_dot_plot__pb2.PlotResponse.FromString,
                _registered_method=True)
        self.StreamPlot = channel.unary_stream(
                '/plot.PlotService/StreamPlot',
                request_serializer=src_dot_protobuf_dot_plot__pb2.PlotRequest.SerializeToString,
                response_deserializer=src_dot_protobuf_dot_plot__pb2.PlotChunk.FromString,
                _registered_method=True)
        self.GenerateMultiplePlots = channel.unary_stream(
                '/plot.PlotService/GenerateMultiplePlots',
                request_serializer=src_dot_protobuf_dot_plot__pb2.MultiPlotRequest.SerializeToString,
                response_deserializer=src_dot_protobuf_dot_plot__pb2.PlotResponse.FromString,
                _registered_method=True)


class PlotServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GeneratePlot(self, request, context):
        """Обычный RPC для получения графика
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamPlot(self, request, context):
        """Стриминг для больших графиков
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateMultiplePlots(self, request, context):
        """Множество графиков
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PlotServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GeneratePlot': grpc.unary_unary_rpc_method_handler(
                    servicer.GeneratePlot,
                    request_deserializer=src_dot_protobuf_dot_plot__pb2.PlotRequest.FromString,
                    response_serializer=src_dot_protobuf_dot_plot__pb2.PlotResponse.SerializeToString,
            ),
            'StreamPlot': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamPlot,
                    request_deserializer=src_dot_protobuf_dot_plot__pb2.PlotRequest.FromString,
                    response_serializer=src_dot_protobuf_dot_plot__pb2.PlotChunk.SerializeToString,
            ),
            'GenerateMultiplePlots': grpc.unary_stream_rpc_method_handler(
                    servicer.GenerateMultiplePlots,
                    request_deserializer=src_dot_protobuf_dot_plot__pb2.MultiPlotRequest.FromString,
                    response_serializer=src_dot_protobuf_dot_plot__pb2.PlotResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'plot.PlotService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('plot.PlotService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PlotService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GeneratePlot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/plot.PlotService/GeneratePlot',
            src_dot_protobuf_dot_plot__pb2.PlotRequest.SerializeToString,
            src_dot_protobuf_dot_plot__pb2.PlotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamPlot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/plot.PlotService/StreamPlot',
            src_dot_protobuf_dot_plot__pb2.PlotRequest.SerializeToString,
            src_dot_protobuf_dot_plot__pb2.PlotChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateMultiplePlots(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/plot.PlotService/GenerateMultiplePlots',
            src_dot_protobuf_dot_plot__pb2.MultiPlotRequest.SerializeToString,
            src_dot_protobuf_dot_plot__pb2.PlotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class MassListServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessMassList = channel.unary_unary(
                '/plot.MassListService/ProcessMassList',
                request_serializer=src_dot_protobuf_dot_plot__pb2.MassListRequest.SerializeToString,
                response_deserializer=src_dot_protobuf_dot_plot__pb2.MassListResponse.FromString,
                _registered_method=True)


class MassListServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def ProcessMassList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MassListServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessMassList': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessMassList,
                    request_deserializer=src_dot_protobuf_dot_plot__pb2.MassListRequest.FromString,
                    response_serializer=src_dot_protobuf_dot_plot__pb2.MassListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'plot.MassListService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('plot.MassListService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MassListService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProcessMassList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/plot.MassListService/ProcessMassList',
            src_dot_protobuf_dot_plot__pb2.MassListRequest.SerializeToString,
            src_dot_protobuf_dot_plot__pb2.MassListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
