// text_service.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: src/protobuf/plot.proto

package plot

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Сообщение для запроса
type TextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Language      string                 `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	Uppercase     bool                   `protobuf:"varint,3,opt,name=uppercase,proto3" json:"uppercase,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"` // массив строк
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextRequest) Reset() {
	*x = TextRequest{}
	mi := &file_src_protobuf_plot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextRequest) ProtoMessage() {}

func (x *TextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_protobuf_plot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextRequest.ProtoReflect.Descriptor instead.
func (*TextRequest) Descriptor() ([]byte, []int) {
	return file_src_protobuf_plot_proto_rawDescGZIP(), []int{0}
}

func (x *TextRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TextRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *TextRequest) GetUppercase() bool {
	if x != nil {
		return x.Uppercase
	}
	return false
}

func (x *TextRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// Сообщение для ответа
type TextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OriginalText  string                 `protobuf:"bytes,1,opt,name=original_text,json=originalText,proto3" json:"original_text,omitempty"`
	ProcessedText string                 `protobuf:"bytes,2,opt,name=processed_text,json=processedText,proto3" json:"processed_text,omitempty"`
	Length        int32                  `protobuf:"varint,3,opt,name=length,proto3" json:"length,omitempty"`
	Language      string                 `protobuf:"bytes,4,opt,name=language,proto3" json:"language,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // словарь
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextResponse) Reset() {
	*x = TextResponse{}
	mi := &file_src_protobuf_plot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextResponse) ProtoMessage() {}

func (x *TextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_protobuf_plot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextResponse.ProtoReflect.Descriptor instead.
func (*TextResponse) Descriptor() ([]byte, []int) {
	return file_src_protobuf_plot_proto_rawDescGZIP(), []int{1}
}

func (x *TextResponse) GetOriginalText() string {
	if x != nil {
		return x.OriginalText
	}
	return ""
}

func (x *TextResponse) GetProcessedText() string {
	if x != nil {
		return x.ProcessedText
	}
	return ""
}

func (x *TextResponse) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *TextResponse) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *TextResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Для стриминга
type TextChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	ChunkNumber   int32                  `protobuf:"varint,2,opt,name=chunk_number,json=chunkNumber,proto3" json:"chunk_number,omitempty"`
	IsLast        bool                   `protobuf:"varint,3,opt,name=is_last,json=isLast,proto3" json:"is_last,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextChunk) Reset() {
	*x = TextChunk{}
	mi := &file_src_protobuf_plot_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextChunk) ProtoMessage() {}

func (x *TextChunk) ProtoReflect() protoreflect.Message {
	mi := &file_src_protobuf_plot_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextChunk.ProtoReflect.Descriptor instead.
func (*TextChunk) Descriptor() ([]byte, []int) {
	return file_src_protobuf_plot_proto_rawDescGZIP(), []int{2}
}

func (x *TextChunk) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *TextChunk) GetChunkNumber() int32 {
	if x != nil {
		return x.ChunkNumber
	}
	return 0
}

func (x *TextChunk) GetIsLast() bool {
	if x != nil {
		return x.IsLast
	}
	return false
}

// Анализ текста
type TextAnalysis struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WordCount     int32                  `protobuf:"varint,1,opt,name=word_count,json=wordCount,proto3" json:"word_count,omitempty"`
	CharCount     int32                  `protobuf:"varint,2,opt,name=char_count,json=charCount,proto3" json:"char_count,omitempty"`
	SentenceCount int32                  `protobuf:"varint,3,opt,name=sentence_count,json=sentenceCount,proto3" json:"sentence_count,omitempty"`
	WordFrequency map[string]int32       `protobuf:"bytes,4,rep,name=word_frequency,json=wordFrequency,proto3" json:"word_frequency,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextAnalysis) Reset() {
	*x = TextAnalysis{}
	mi := &file_src_protobuf_plot_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextAnalysis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextAnalysis) ProtoMessage() {}

func (x *TextAnalysis) ProtoReflect() protoreflect.Message {
	mi := &file_src_protobuf_plot_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextAnalysis.ProtoReflect.Descriptor instead.
func (*TextAnalysis) Descriptor() ([]byte, []int) {
	return file_src_protobuf_plot_proto_rawDescGZIP(), []int{3}
}

func (x *TextAnalysis) GetWordCount() int32 {
	if x != nil {
		return x.WordCount
	}
	return 0
}

func (x *TextAnalysis) GetCharCount() int32 {
	if x != nil {
		return x.CharCount
	}
	return 0
}

func (x *TextAnalysis) GetSentenceCount() int32 {
	if x != nil {
		return x.SentenceCount
	}
	return 0
}

func (x *TextAnalysis) GetWordFrequency() map[string]int32 {
	if x != nil {
		return x.WordFrequency
	}
	return nil
}

// Для чата
type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_src_protobuf_plot_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_src_protobuf_plot_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_src_protobuf_plot_proto_rawDescGZIP(), []int{4}
}

func (x *ChatMessage) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ChatMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ChatMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_src_protobuf_plot_proto protoreflect.FileDescriptor

const file_src_protobuf_plot_proto_rawDesc = "" +
	"\n" +
	"\x17src/protobuf/plot.proto\x12\x04plot\"o\n" +
	"\vTextRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\x12\x1c\n" +
	"\tuppercase\x18\x03 \x01(\bR\tuppercase\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\"\x89\x02\n" +
	"\fTextResponse\x12#\n" +
	"\roriginal_text\x18\x01 \x01(\tR\foriginalText\x12%\n" +
	"\x0eprocessed_text\x18\x02 \x01(\tR\rprocessedText\x12\x16\n" +
	"\x06length\x18\x03 \x01(\x05R\x06length\x12\x1a\n" +
	"\blanguage\x18\x04 \x01(\tR\blanguage\x12<\n" +
	"\bmetadata\x18\x05 \x03(\v2 .plot.TextResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"a\n" +
	"\tTextChunk\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12!\n" +
	"\fchunk_number\x18\x02 \x01(\x05R\vchunkNumber\x12\x17\n" +
	"\ais_last\x18\x03 \x01(\bR\x06isLast\"\x83\x02\n" +
	"\fTextAnalysis\x12\x1d\n" +
	"\n" +
	"word_count\x18\x01 \x01(\x05R\twordCount\x12\x1d\n" +
	"\n" +
	"char_count\x18\x02 \x01(\x05R\tcharCount\x12%\n" +
	"\x0esentence_count\x18\x03 \x01(\x05R\rsentenceCount\x12L\n" +
	"\x0eword_frequency\x18\x04 \x03(\v2%.plot.TextAnalysis.WordFrequencyEntryR\rwordFrequency\x1a@\n" +
	"\x12WordFrequencyEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"^\n" +
	"\vChatMessage\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp2\xf2\x01\n" +
	"\vTextService\x124\n" +
	"\vProcessText\x12\x11.plot.TextRequest\x1a\x12.plot.TextResponse\x129\n" +
	"\x11StreamProcessText\x12\x11.plot.TextRequest\x1a\x0f.plot.TextChunk0\x01\x12:\n" +
	"\x11AnalyzeTextStream\x12\x0f.plot.TextChunk\x1a\x12.plot.TextAnalysis(\x01\x126\n" +
	"\n" +
	"ChatStream\x12\x11.plot.ChatMessage\x1a\x11.plot.ChatMessage(\x010\x01B\x18Z\x16src/protobuf/plot;plotb\x06proto3"

var (
	file_src_protobuf_plot_proto_rawDescOnce sync.Once
	file_src_protobuf_plot_proto_rawDescData []byte
)

func file_src_protobuf_plot_proto_rawDescGZIP() []byte {
	file_src_protobuf_plot_proto_rawDescOnce.Do(func() {
		file_src_protobuf_plot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_src_protobuf_plot_proto_rawDesc), len(file_src_protobuf_plot_proto_rawDesc)))
	})
	return file_src_protobuf_plot_proto_rawDescData
}

var file_src_protobuf_plot_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_src_protobuf_plot_proto_goTypes = []any{
	(*TextRequest)(nil),  // 0: plot.TextRequest
	(*TextResponse)(nil), // 1: plot.TextResponse
	(*TextChunk)(nil),    // 2: plot.TextChunk
	(*TextAnalysis)(nil), // 3: plot.TextAnalysis
	(*ChatMessage)(nil),  // 4: plot.ChatMessage
	nil,                  // 5: plot.TextResponse.MetadataEntry
	nil,                  // 6: plot.TextAnalysis.WordFrequencyEntry
}
var file_src_protobuf_plot_proto_depIdxs = []int32{
	5, // 0: plot.TextResponse.metadata:type_name -> plot.TextResponse.MetadataEntry
	6, // 1: plot.TextAnalysis.word_frequency:type_name -> plot.TextAnalysis.WordFrequencyEntry
	0, // 2: plot.TextService.ProcessText:input_type -> plot.TextRequest
	0, // 3: plot.TextService.StreamProcessText:input_type -> plot.TextRequest
	2, // 4: plot.TextService.AnalyzeTextStream:input_type -> plot.TextChunk
	4, // 5: plot.TextService.ChatStream:input_type -> plot.ChatMessage
	1, // 6: plot.TextService.ProcessText:output_type -> plot.TextResponse
	2, // 7: plot.TextService.StreamProcessText:output_type -> plot.TextChunk
	3, // 8: plot.TextService.AnalyzeTextStream:output_type -> plot.TextAnalysis
	4, // 9: plot.TextService.ChatStream:output_type -> plot.ChatMessage
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_src_protobuf_plot_proto_init() }
func file_src_protobuf_plot_proto_init() {
	if File_src_protobuf_plot_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_src_protobuf_plot_proto_rawDesc), len(file_src_protobuf_plot_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_src_protobuf_plot_proto_goTypes,
		DependencyIndexes: file_src_protobuf_plot_proto_depIdxs,
		MessageInfos:      file_src_protobuf_plot_proto_msgTypes,
	}.Build()
	File_src_protobuf_plot_proto = out.File
	file_src_protobuf_plot_proto_goTypes = nil
	file_src_protobuf_plot_proto_depIdxs = nil
}
