// text_service.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: src/protobuf/plot.proto

package plot

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Сообщение для запроса
type TextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Language      string                 `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	Uppercase     bool                   `protobuf:"varint,3,opt,name=uppercase,proto3" json:"uppercase,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"` // массив строк
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextRequest) Reset() {
	*x = TextRequest{}
	mi := &file_src_protobuf_plot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextRequest) ProtoMessage() {}

func (x *TextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_protobuf_plot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextRequest.ProtoReflect.Descriptor instead.
func (*TextRequest) Descriptor() ([]byte, []int) {
	return file_src_protobuf_plot_proto_rawDescGZIP(), []int{0}
}

func (x *TextRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TextRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *TextRequest) GetUppercase() bool {
	if x != nil {
		return x.Uppercase
	}
	return false
}

func (x *TextRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// Сообщение для ответа
type TextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OriginalText  string                 `protobuf:"bytes,1,opt,name=original_text,json=originalText,proto3" json:"original_text,omitempty"`
	ProcessedText string                 `protobuf:"bytes,2,opt,name=processed_text,json=processedText,proto3" json:"processed_text,omitempty"`
	Length        int32                  `protobuf:"varint,3,opt,name=length,proto3" json:"length,omitempty"`
	Language      string                 `protobuf:"bytes,4,opt,name=language,proto3" json:"language,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // словарь
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextResponse) Reset() {
	*x = TextResponse{}
	mi := &file_src_protobuf_plot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextResponse) ProtoMessage() {}

func (x *TextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_protobuf_plot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextResponse.ProtoReflect.Descriptor instead.
func (*TextResponse) Descriptor() ([]byte, []int) {
	return file_src_protobuf_plot_proto_rawDescGZIP(), []int{1}
}

func (x *TextResponse) GetOriginalText() string {
	if x != nil {
		return x.OriginalText
	}
	return ""
}

func (x *TextResponse) GetProcessedText() string {
	if x != nil {
		return x.ProcessedText
	}
	return ""
}

func (x *TextResponse) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *TextResponse) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *TextResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type PlotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	XValues       []float64              `protobuf:"fixed64,1,rep,packed,name=x_values,json=xValues,proto3" json:"x_values,omitempty"`
	YValues       []float64              `protobuf:"fixed64,2,rep,packed,name=y_values,json=yValues,proto3" json:"y_values,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	XLabel        string                 `protobuf:"bytes,4,opt,name=x_label,json=xLabel,proto3" json:"x_label,omitempty"`
	YLabel        string                 `protobuf:"bytes,5,opt,name=y_label,json=yLabel,proto3" json:"y_label,omitempty"`
	PlotType      string                 `protobuf:"bytes,6,opt,name=plot_type,json=plotType,proto3" json:"plot_type,omitempty"` // line, bar, scatter, hist
	Color         string                 `protobuf:"bytes,7,opt,name=color,proto3" json:"color,omitempty"`
	Grid          bool                   `protobuf:"varint,8,opt,name=grid,proto3" json:"grid,omitempty"`
	Width         int32                  `protobuf:"varint,9,opt,name=width,proto3" json:"width,omitempty"`                                                                               // ширина в дюймах
	Height        int32                  `protobuf:"varint,10,opt,name=height,proto3" json:"height,omitempty"`                                                                            // высота в дюймах
	Dpi           int32                  `protobuf:"varint,11,opt,name=dpi,proto3" json:"dpi,omitempty"`                                                                                  // разрешение
	Format        string                 `protobuf:"bytes,12,opt,name=format,proto3" json:"format,omitempty"`                                                                             // png, svg, pdf, jpeg
	Options       map[string]string      `protobuf:"bytes,13,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // дополнительные параметры
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlotRequest) Reset() {
	*x = PlotRequest{}
	mi := &file_src_protobuf_plot_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlotRequest) ProtoMessage() {}

func (x *PlotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_protobuf_plot_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlotRequest.ProtoReflect.Descriptor instead.
func (*PlotRequest) Descriptor() ([]byte, []int) {
	return file_src_protobuf_plot_proto_rawDescGZIP(), []int{2}
}

func (x *PlotRequest) GetXValues() []float64 {
	if x != nil {
		return x.XValues
	}
	return nil
}

func (x *PlotRequest) GetYValues() []float64 {
	if x != nil {
		return x.YValues
	}
	return nil
}

func (x *PlotRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PlotRequest) GetXLabel() string {
	if x != nil {
		return x.XLabel
	}
	return ""
}

func (x *PlotRequest) GetYLabel() string {
	if x != nil {
		return x.YLabel
	}
	return ""
}

func (x *PlotRequest) GetPlotType() string {
	if x != nil {
		return x.PlotType
	}
	return ""
}

func (x *PlotRequest) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *PlotRequest) GetGrid() bool {
	if x != nil {
		return x.Grid
	}
	return false
}

func (x *PlotRequest) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *PlotRequest) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *PlotRequest) GetDpi() int32 {
	if x != nil {
		return x.Dpi
	}
	return 0
}

func (x *PlotRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *PlotRequest) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

type PlotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageData     []byte                 `protobuf:"bytes,1,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"`        // бинарные данные изображения
	Format        string                 `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`                               // png, svg, pdf, jpeg
	SizeBytes     int64                  `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`       // размер в байтах
	MimeType      string                 `protobuf:"bytes,4,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`           // image/png, image/svg+xml, etc.
	GeneratedAt   int64                  `protobuf:"varint,5,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"` // timestamp
	Info          *PlotInfo              `protobuf:"bytes,6,opt,name=info,proto3" json:"info,omitempty"`                                   // метаданные
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlotResponse) Reset() {
	*x = PlotResponse{}
	mi := &file_src_protobuf_plot_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlotResponse) ProtoMessage() {}

func (x *PlotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_protobuf_plot_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlotResponse.ProtoReflect.Descriptor instead.
func (*PlotResponse) Descriptor() ([]byte, []int) {
	return file_src_protobuf_plot_proto_rawDescGZIP(), []int{3}
}

func (x *PlotResponse) GetImageData() []byte {
	if x != nil {
		return x.ImageData
	}
	return nil
}

func (x *PlotResponse) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *PlotResponse) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *PlotResponse) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *PlotResponse) GetGeneratedAt() int64 {
	if x != nil {
		return x.GeneratedAt
	}
	return 0
}

func (x *PlotResponse) GetInfo() *PlotInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type PlotChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkData     []byte                 `protobuf:"bytes,1,opt,name=chunk_data,json=chunkData,proto3" json:"chunk_data,omitempty"`
	ChunkNumber   int32                  `protobuf:"varint,2,opt,name=chunk_number,json=chunkNumber,proto3" json:"chunk_number,omitempty"`
	IsLast        bool                   `protobuf:"varint,3,opt,name=is_last,json=isLast,proto3" json:"is_last,omitempty"`
	TotalSize     int64                  `protobuf:"varint,4,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlotChunk) Reset() {
	*x = PlotChunk{}
	mi := &file_src_protobuf_plot_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlotChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlotChunk) ProtoMessage() {}

func (x *PlotChunk) ProtoReflect() protoreflect.Message {
	mi := &file_src_protobuf_plot_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlotChunk.ProtoReflect.Descriptor instead.
func (*PlotChunk) Descriptor() ([]byte, []int) {
	return file_src_protobuf_plot_proto_rawDescGZIP(), []int{4}
}

func (x *PlotChunk) GetChunkData() []byte {
	if x != nil {
		return x.ChunkData
	}
	return nil
}

func (x *PlotChunk) GetChunkNumber() int32 {
	if x != nil {
		return x.ChunkNumber
	}
	return 0
}

func (x *PlotChunk) GetIsLast() bool {
	if x != nil {
		return x.IsLast
	}
	return false
}

func (x *PlotChunk) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

type MultiPlotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plots         []*PlotRequest         `protobuf:"bytes,1,rep,name=plots,proto3" json:"plots,omitempty"`
	Layout        string                 `protobuf:"bytes,2,opt,name=layout,proto3" json:"layout,omitempty"` // grid, horizontal, vertical
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultiPlotRequest) Reset() {
	*x = MultiPlotRequest{}
	mi := &file_src_protobuf_plot_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultiPlotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiPlotRequest) ProtoMessage() {}

func (x *MultiPlotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_protobuf_plot_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiPlotRequest.ProtoReflect.Descriptor instead.
func (*MultiPlotRequest) Descriptor() ([]byte, []int) {
	return file_src_protobuf_plot_proto_rawDescGZIP(), []int{5}
}

func (x *MultiPlotRequest) GetPlots() []*PlotRequest {
	if x != nil {
		return x.Plots
	}
	return nil
}

func (x *MultiPlotRequest) GetLayout() string {
	if x != nil {
		return x.Layout
	}
	return ""
}

type PlotInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Width         int32                  `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Dpi           int32                  `protobuf:"varint,4,opt,name=dpi,proto3" json:"dpi,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlotInfo) Reset() {
	*x = PlotInfo{}
	mi := &file_src_protobuf_plot_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlotInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlotInfo) ProtoMessage() {}

func (x *PlotInfo) ProtoReflect() protoreflect.Message {
	mi := &file_src_protobuf_plot_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlotInfo.ProtoReflect.Descriptor instead.
func (*PlotInfo) Descriptor() ([]byte, []int) {
	return file_src_protobuf_plot_proto_rawDescGZIP(), []int{6}
}

func (x *PlotInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PlotInfo) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *PlotInfo) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *PlotInfo) GetDpi() int32 {
	if x != nil {
		return x.Dpi
	}
	return 0
}

type ElementRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Min           int32                  `protobuf:"varint,1,opt,name=min,proto3" json:"min,omitempty"`
	Max           int32                  `protobuf:"varint,2,opt,name=max,proto3" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ElementRange) Reset() {
	*x = ElementRange{}
	mi := &file_src_protobuf_plot_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ElementRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElementRange) ProtoMessage() {}

func (x *ElementRange) ProtoReflect() protoreflect.Message {
	mi := &file_src_protobuf_plot_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElementRange.ProtoReflect.Descriptor instead.
func (*ElementRange) Descriptor() ([]byte, []int) {
	return file_src_protobuf_plot_proto_rawDescGZIP(), []int{7}
}

func (x *ElementRange) GetMin() int32 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *ElementRange) GetMax() int32 {
	if x != nil {
		return x.Max
	}
	return 0
}

type MassListRequest struct {
	state          protoimpl.MessageState   `protogen:"open.v1"`
	SpectraName    string                   `protobuf:"bytes,1,opt,name=spectra_name,json=spectraName,proto3" json:"spectra_name,omitempty"`
	LowPercentile  float32                  `protobuf:"fixed32,2,opt,name=low_percentile,json=lowPercentile,proto3" json:"low_percentile,omitempty"`
	HighPercentile float32                  `protobuf:"fixed32,3,opt,name=high_percentile,json=highPercentile,proto3" json:"high_percentile,omitempty"`
	RelError       float32                  `protobuf:"fixed32,4,opt,name=rel_error,json=relError,proto3" json:"rel_error,omitempty"`
	ChargeMax      int32                    `protobuf:"varint,5,opt,name=charge_max,json=chargeMax,proto3" json:"charge_max,omitempty"`
	BruttoDict     map[string]*ElementRange `protobuf:"bytes,6,rep,name=brutto_dict,json=bruttoDict,proto3" json:"brutto_dict,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Protocole      string                   `protobuf:"bytes,7,opt,name=protocole,proto3" json:"protocole,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MassListRequest) Reset() {
	*x = MassListRequest{}
	mi := &file_src_protobuf_plot_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MassListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MassListRequest) ProtoMessage() {}

func (x *MassListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_protobuf_plot_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MassListRequest.ProtoReflect.Descriptor instead.
func (*MassListRequest) Descriptor() ([]byte, []int) {
	return file_src_protobuf_plot_proto_rawDescGZIP(), []int{8}
}

func (x *MassListRequest) GetSpectraName() string {
	if x != nil {
		return x.SpectraName
	}
	return ""
}

func (x *MassListRequest) GetLowPercentile() float32 {
	if x != nil {
		return x.LowPercentile
	}
	return 0
}

func (x *MassListRequest) GetHighPercentile() float32 {
	if x != nil {
		return x.HighPercentile
	}
	return 0
}

func (x *MassListRequest) GetRelError() float32 {
	if x != nil {
		return x.RelError
	}
	return 0
}

func (x *MassListRequest) GetChargeMax() int32 {
	if x != nil {
		return x.ChargeMax
	}
	return 0
}

func (x *MassListRequest) GetBruttoDict() map[string]*ElementRange {
	if x != nil {
		return x.BruttoDict
	}
	return nil
}

func (x *MassListRequest) GetProtocole() string {
	if x != nil {
		return x.Protocole
	}
	return ""
}

type MassListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageData     []byte                 `protobuf:"bytes,1,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"`
	Format        string                 `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	MimeType      string                 `protobuf:"bytes,4,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	GeneratedAt   int64                  `protobuf:"varint,5,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"`
	Info          *PlotInfo              `protobuf:"bytes,6,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MassListResponse) Reset() {
	*x = MassListResponse{}
	mi := &file_src_protobuf_plot_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MassListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MassListResponse) ProtoMessage() {}

func (x *MassListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_protobuf_plot_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MassListResponse.ProtoReflect.Descriptor instead.
func (*MassListResponse) Descriptor() ([]byte, []int) {
	return file_src_protobuf_plot_proto_rawDescGZIP(), []int{9}
}

func (x *MassListResponse) GetImageData() []byte {
	if x != nil {
		return x.ImageData
	}
	return nil
}

func (x *MassListResponse) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *MassListResponse) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *MassListResponse) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *MassListResponse) GetGeneratedAt() int64 {
	if x != nil {
		return x.GeneratedAt
	}
	return 0
}

func (x *MassListResponse) GetInfo() *PlotInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

var File_src_protobuf_plot_proto protoreflect.FileDescriptor

const file_src_protobuf_plot_proto_rawDesc = "" +
	"\n" +
	"\x17src/protobuf/plot.proto\x12\x04plot\"o\n" +
	"\vTextRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\x12\x1c\n" +
	"\tuppercase\x18\x03 \x01(\bR\tuppercase\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\"\x89\x02\n" +
	"\fTextResponse\x12#\n" +
	"\roriginal_text\x18\x01 \x01(\tR\foriginalText\x12%\n" +
	"\x0eprocessed_text\x18\x02 \x01(\tR\rprocessedText\x12\x16\n" +
	"\x06length\x18\x03 \x01(\x05R\x06length\x12\x1a\n" +
	"\blanguage\x18\x04 \x01(\tR\blanguage\x12<\n" +
	"\bmetadata\x18\x05 \x03(\v2 .plot.TextResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa0\x03\n" +
	"\vPlotRequest\x12\x19\n" +
	"\bx_values\x18\x01 \x03(\x01R\axValues\x12\x19\n" +
	"\by_values\x18\x02 \x03(\x01R\ayValues\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x17\n" +
	"\ax_label\x18\x04 \x01(\tR\x06xLabel\x12\x17\n" +
	"\ay_label\x18\x05 \x01(\tR\x06yLabel\x12\x1b\n" +
	"\tplot_type\x18\x06 \x01(\tR\bplotType\x12\x14\n" +
	"\x05color\x18\a \x01(\tR\x05color\x12\x12\n" +
	"\x04grid\x18\b \x01(\bR\x04grid\x12\x14\n" +
	"\x05width\x18\t \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\n" +
	" \x01(\x05R\x06height\x12\x10\n" +
	"\x03dpi\x18\v \x01(\x05R\x03dpi\x12\x16\n" +
	"\x06format\x18\f \x01(\tR\x06format\x128\n" +
	"\aoptions\x18\r \x03(\v2\x1e.plot.PlotRequest.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc8\x01\n" +
	"\fPlotResponse\x12\x1d\n" +
	"\n" +
	"image_data\x18\x01 \x01(\fR\timageData\x12\x16\n" +
	"\x06format\x18\x02 \x01(\tR\x06format\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x03R\tsizeBytes\x12\x1b\n" +
	"\tmime_type\x18\x04 \x01(\tR\bmimeType\x12!\n" +
	"\fgenerated_at\x18\x05 \x01(\x03R\vgeneratedAt\x12\"\n" +
	"\x04info\x18\x06 \x01(\v2\x0e.plot.PlotInfoR\x04info\"\x85\x01\n" +
	"\tPlotChunk\x12\x1d\n" +
	"\n" +
	"chunk_data\x18\x01 \x01(\fR\tchunkData\x12!\n" +
	"\fchunk_number\x18\x02 \x01(\x05R\vchunkNumber\x12\x17\n" +
	"\ais_last\x18\x03 \x01(\bR\x06isLast\x12\x1d\n" +
	"\n" +
	"total_size\x18\x04 \x01(\x03R\ttotalSize\"S\n" +
	"\x10MultiPlotRequest\x12'\n" +
	"\x05plots\x18\x01 \x03(\v2\x11.plot.PlotRequestR\x05plots\x12\x16\n" +
	"\x06layout\x18\x02 \x01(\tR\x06layout\"`\n" +
	"\bPlotInfo\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x14\n" +
	"\x05width\x18\x02 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x05R\x06height\x12\x10\n" +
	"\x03dpi\x18\x04 \x01(\x05R\x03dpi\"2\n" +
	"\fElementRange\x12\x10\n" +
	"\x03min\x18\x01 \x01(\x05R\x03min\x12\x10\n" +
	"\x03max\x18\x02 \x01(\x05R\x03max\"\xf9\x02\n" +
	"\x0fMassListRequest\x12!\n" +
	"\fspectra_name\x18\x01 \x01(\tR\vspectraName\x12%\n" +
	"\x0elow_percentile\x18\x02 \x01(\x02R\rlowPercentile\x12'\n" +
	"\x0fhigh_percentile\x18\x03 \x01(\x02R\x0ehighPercentile\x12\x1b\n" +
	"\trel_error\x18\x04 \x01(\x02R\brelError\x12\x1d\n" +
	"\n" +
	"charge_max\x18\x05 \x01(\x05R\tchargeMax\x12F\n" +
	"\vbrutto_dict\x18\x06 \x03(\v2%.plot.MassListRequest.BruttoDictEntryR\n" +
	"bruttoDict\x12\x1c\n" +
	"\tprotocole\x18\a \x01(\tR\tprotocole\x1aQ\n" +
	"\x0fBruttoDictEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.plot.ElementRangeR\x05value:\x028\x01\"\xcc\x01\n" +
	"\x10MassListResponse\x12\x1d\n" +
	"\n" +
	"image_data\x18\x01 \x01(\fR\timageData\x12\x16\n" +
	"\x06format\x18\x02 \x01(\tR\x06format\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x03R\tsizeBytes\x12\x1b\n" +
	"\tmime_type\x18\x04 \x01(\tR\bmimeType\x12!\n" +
	"\fgenerated_at\x18\x05 \x01(\x03R\vgeneratedAt\x12\"\n" +
	"\x04info\x18\x06 \x01(\v2\x0e.plot.PlotInfoR\x04info2C\n" +
	"\vTextService\x124\n" +
	"\vProcessText\x12\x11.plot.TextRequest\x1a\x12.plot.TextResponse2\xbf\x01\n" +
	"\vPlotService\x125\n" +
	"\fGeneratePlot\x12\x11.plot.PlotRequest\x1a\x12.plot.PlotResponse\x122\n" +
	"\n" +
	"StreamPlot\x12\x11.plot.PlotRequest\x1a\x0f.plot.PlotChunk0\x01\x12E\n" +
	"\x15GenerateMultiplePlots\x12\x16.plot.MultiPlotRequest\x1a\x12.plot.PlotResponse0\x012S\n" +
	"\x0fMassListService\x12@\n" +
	"\x0fProcessMassList\x12\x15.plot.MassListRequest\x1a\x16.plot.MassListResponseB\x18Z\x16src/protobuf/plot;plotb\x06proto3"

var (
	file_src_protobuf_plot_proto_rawDescOnce sync.Once
	file_src_protobuf_plot_proto_rawDescData []byte
)

func file_src_protobuf_plot_proto_rawDescGZIP() []byte {
	file_src_protobuf_plot_proto_rawDescOnce.Do(func() {
		file_src_protobuf_plot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_src_protobuf_plot_proto_rawDesc), len(file_src_protobuf_plot_proto_rawDesc)))
	})
	return file_src_protobuf_plot_proto_rawDescData
}

var file_src_protobuf_plot_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_src_protobuf_plot_proto_goTypes = []any{
	(*TextRequest)(nil),      // 0: plot.TextRequest
	(*TextResponse)(nil),     // 1: plot.TextResponse
	(*PlotRequest)(nil),      // 2: plot.PlotRequest
	(*PlotResponse)(nil),     // 3: plot.PlotResponse
	(*PlotChunk)(nil),        // 4: plot.PlotChunk
	(*MultiPlotRequest)(nil), // 5: plot.MultiPlotRequest
	(*PlotInfo)(nil),         // 6: plot.PlotInfo
	(*ElementRange)(nil),     // 7: plot.ElementRange
	(*MassListRequest)(nil),  // 8: plot.MassListRequest
	(*MassListResponse)(nil), // 9: plot.MassListResponse
	nil,                      // 10: plot.TextResponse.MetadataEntry
	nil,                      // 11: plot.PlotRequest.OptionsEntry
	nil,                      // 12: plot.MassListRequest.BruttoDictEntry
}
var file_src_protobuf_plot_proto_depIdxs = []int32{
	10, // 0: plot.TextResponse.metadata:type_name -> plot.TextResponse.MetadataEntry
	11, // 1: plot.PlotRequest.options:type_name -> plot.PlotRequest.OptionsEntry
	6,  // 2: plot.PlotResponse.info:type_name -> plot.PlotInfo
	2,  // 3: plot.MultiPlotRequest.plots:type_name -> plot.PlotRequest
	12, // 4: plot.MassListRequest.brutto_dict:type_name -> plot.MassListRequest.BruttoDictEntry
	6,  // 5: plot.MassListResponse.info:type_name -> plot.PlotInfo
	7,  // 6: plot.MassListRequest.BruttoDictEntry.value:type_name -> plot.ElementRange
	0,  // 7: plot.TextService.ProcessText:input_type -> plot.TextRequest
	2,  // 8: plot.PlotService.GeneratePlot:input_type -> plot.PlotRequest
	2,  // 9: plot.PlotService.StreamPlot:input_type -> plot.PlotRequest
	5,  // 10: plot.PlotService.GenerateMultiplePlots:input_type -> plot.MultiPlotRequest
	8,  // 11: plot.MassListService.ProcessMassList:input_type -> plot.MassListRequest
	1,  // 12: plot.TextService.ProcessText:output_type -> plot.TextResponse
	3,  // 13: plot.PlotService.GeneratePlot:output_type -> plot.PlotResponse
	4,  // 14: plot.PlotService.StreamPlot:output_type -> plot.PlotChunk
	3,  // 15: plot.PlotService.GenerateMultiplePlots:output_type -> plot.PlotResponse
	9,  // 16: plot.MassListService.ProcessMassList:output_type -> plot.MassListResponse
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_src_protobuf_plot_proto_init() }
func file_src_protobuf_plot_proto_init() {
	if File_src_protobuf_plot_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_src_protobuf_plot_proto_rawDesc), len(file_src_protobuf_plot_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_src_protobuf_plot_proto_goTypes,
		DependencyIndexes: file_src_protobuf_plot_proto_depIdxs,
		MessageInfos:      file_src_protobuf_plot_proto_msgTypes,
	}.Build()
	File_src_protobuf_plot_proto = out.File
	file_src_protobuf_plot_proto_goTypes = nil
	file_src_protobuf_plot_proto_depIdxs = nil
}
