// text_service.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: src/protobuf/plot.proto

package plot

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlotInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Width         int32                  `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Dpi           int32                  `protobuf:"varint,4,opt,name=dpi,proto3" json:"dpi,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlotInfo) Reset() {
	*x = PlotInfo{}
	mi := &file_src_protobuf_plot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlotInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlotInfo) ProtoMessage() {}

func (x *PlotInfo) ProtoReflect() protoreflect.Message {
	mi := &file_src_protobuf_plot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlotInfo.ProtoReflect.Descriptor instead.
func (*PlotInfo) Descriptor() ([]byte, []int) {
	return file_src_protobuf_plot_proto_rawDescGZIP(), []int{0}
}

func (x *PlotInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PlotInfo) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *PlotInfo) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *PlotInfo) GetDpi() int32 {
	if x != nil {
		return x.Dpi
	}
	return 0
}

type BruttoRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Min           int32                  `protobuf:"varint,1,opt,name=min,proto3" json:"min,omitempty"`
	Max           int32                  `protobuf:"varint,2,opt,name=max,proto3" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BruttoRange) Reset() {
	*x = BruttoRange{}
	mi := &file_src_protobuf_plot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BruttoRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BruttoRange) ProtoMessage() {}

func (x *BruttoRange) ProtoReflect() protoreflect.Message {
	mi := &file_src_protobuf_plot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BruttoRange.ProtoReflect.Descriptor instead.
func (*BruttoRange) Descriptor() ([]byte, []int) {
	return file_src_protobuf_plot_proto_rawDescGZIP(), []int{1}
}

func (x *BruttoRange) GetMin() int32 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *BruttoRange) GetMax() int32 {
	if x != nil {
		return x.Max
	}
	return 0
}

type MassListRequest struct {
	state          protoimpl.MessageState  `protogen:"open.v1"`
	SpectraName    string                  `protobuf:"bytes,1,opt,name=spectra_name,json=spectraName,proto3" json:"spectra_name,omitempty"`
	LowPercentile  float32                 `protobuf:"fixed32,2,opt,name=low_percentile,json=lowPercentile,proto3" json:"low_percentile,omitempty"`
	HighPercentile float32                 `protobuf:"fixed32,3,opt,name=high_percentile,json=highPercentile,proto3" json:"high_percentile,omitempty"`
	RelError       float32                 `protobuf:"fixed32,4,opt,name=rel_error,json=relError,proto3" json:"rel_error,omitempty"`
	ChargeMax      int32                   `protobuf:"varint,5,opt,name=charge_max,json=chargeMax,proto3" json:"charge_max,omitempty"`
	BruttoDict     map[string]*BruttoRange `protobuf:"bytes,6,rep,name=brutto_dict,json=bruttoDict,proto3" json:"brutto_dict,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Protocole      string                  `protobuf:"bytes,7,opt,name=protocole,proto3" json:"protocole,omitempty"`
	SpectraPath    string                  `protobuf:"bytes,8,opt,name=spectra_path,json=spectraPath,proto3" json:"spectra_path,omitempty"`
	Width          int32                   `protobuf:"varint,9,opt,name=width,proto3" json:"width,omitempty"`
	Height         int32                   `protobuf:"varint,10,opt,name=height,proto3" json:"height,omitempty"`
	Dpi            int32                   `protobuf:"varint,11,opt,name=dpi,proto3" json:"dpi,omitempty"`
	Format         string                  `protobuf:"bytes,12,opt,name=format,proto3" json:"format,omitempty"`
	Options        map[string]string       `protobuf:"bytes,13,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MassListRequest) Reset() {
	*x = MassListRequest{}
	mi := &file_src_protobuf_plot_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MassListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MassListRequest) ProtoMessage() {}

func (x *MassListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_protobuf_plot_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MassListRequest.ProtoReflect.Descriptor instead.
func (*MassListRequest) Descriptor() ([]byte, []int) {
	return file_src_protobuf_plot_proto_rawDescGZIP(), []int{2}
}

func (x *MassListRequest) GetSpectraName() string {
	if x != nil {
		return x.SpectraName
	}
	return ""
}

func (x *MassListRequest) GetLowPercentile() float32 {
	if x != nil {
		return x.LowPercentile
	}
	return 0
}

func (x *MassListRequest) GetHighPercentile() float32 {
	if x != nil {
		return x.HighPercentile
	}
	return 0
}

func (x *MassListRequest) GetRelError() float32 {
	if x != nil {
		return x.RelError
	}
	return 0
}

func (x *MassListRequest) GetChargeMax() int32 {
	if x != nil {
		return x.ChargeMax
	}
	return 0
}

func (x *MassListRequest) GetBruttoDict() map[string]*BruttoRange {
	if x != nil {
		return x.BruttoDict
	}
	return nil
}

func (x *MassListRequest) GetProtocole() string {
	if x != nil {
		return x.Protocole
	}
	return ""
}

func (x *MassListRequest) GetSpectraPath() string {
	if x != nil {
		return x.SpectraPath
	}
	return ""
}

func (x *MassListRequest) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *MassListRequest) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *MassListRequest) GetDpi() int32 {
	if x != nil {
		return x.Dpi
	}
	return 0
}

func (x *MassListRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *MassListRequest) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

type MassListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageData     []byte                 `protobuf:"bytes,1,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"`
	Format        string                 `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	MimeType      string                 `protobuf:"bytes,4,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	GeneratedAt   int64                  `protobuf:"varint,5,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"`
	Info          *PlotInfo              `protobuf:"bytes,6,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MassListResponse) Reset() {
	*x = MassListResponse{}
	mi := &file_src_protobuf_plot_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MassListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MassListResponse) ProtoMessage() {}

func (x *MassListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_protobuf_plot_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MassListResponse.ProtoReflect.Descriptor instead.
func (*MassListResponse) Descriptor() ([]byte, []int) {
	return file_src_protobuf_plot_proto_rawDescGZIP(), []int{3}
}

func (x *MassListResponse) GetImageData() []byte {
	if x != nil {
		return x.ImageData
	}
	return nil
}

func (x *MassListResponse) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *MassListResponse) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *MassListResponse) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *MassListResponse) GetGeneratedAt() int64 {
	if x != nil {
		return x.GeneratedAt
	}
	return 0
}

func (x *MassListResponse) GetInfo() *PlotInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

var File_src_protobuf_plot_proto protoreflect.FileDescriptor

const file_src_protobuf_plot_proto_rawDesc = "" +
	"\n" +
	"\x17src/protobuf/plot.proto\x12\x04plot\"`\n" +
	"\bPlotInfo\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x14\n" +
	"\x05width\x18\x02 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x05R\x06height\x12\x10\n" +
	"\x03dpi\x18\x04 \x01(\x05R\x03dpi\"1\n" +
	"\vBruttoRange\x12\x10\n" +
	"\x03min\x18\x01 \x01(\x05R\x03min\x12\x10\n" +
	"\x03max\x18\x02 \x01(\x05R\x03max\"\xed\x04\n" +
	"\x0fMassListRequest\x12!\n" +
	"\fspectra_name\x18\x01 \x01(\tR\vspectraName\x12%\n" +
	"\x0elow_percentile\x18\x02 \x01(\x02R\rlowPercentile\x12'\n" +
	"\x0fhigh_percentile\x18\x03 \x01(\x02R\x0ehighPercentile\x12\x1b\n" +
	"\trel_error\x18\x04 \x01(\x02R\brelError\x12\x1d\n" +
	"\n" +
	"charge_max\x18\x05 \x01(\x05R\tchargeMax\x12F\n" +
	"\vbrutto_dict\x18\x06 \x03(\v2%.plot.MassListRequest.BruttoDictEntryR\n" +
	"bruttoDict\x12\x1c\n" +
	"\tprotocole\x18\a \x01(\tR\tprotocole\x12!\n" +
	"\fspectra_path\x18\b \x01(\tR\vspectraPath\x12\x14\n" +
	"\x05width\x18\t \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\n" +
	" \x01(\x05R\x06height\x12\x10\n" +
	"\x03dpi\x18\v \x01(\x05R\x03dpi\x12\x16\n" +
	"\x06format\x18\f \x01(\tR\x06format\x12<\n" +
	"\aoptions\x18\r \x03(\v2\".plot.MassListRequest.OptionsEntryR\aoptions\x1aP\n" +
	"\x0fBruttoDictEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12'\n" +
	"\x05value\x18\x02 \x01(\v2\x11.plot.BruttoRangeR\x05value:\x028\x01\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xcc\x01\n" +
	"\x10MassListResponse\x12\x1d\n" +
	"\n" +
	"image_data\x18\x01 \x01(\fR\timageData\x12\x16\n" +
	"\x06format\x18\x02 \x01(\tR\x06format\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x03R\tsizeBytes\x12\x1b\n" +
	"\tmime_type\x18\x04 \x01(\tR\bmimeType\x12!\n" +
	"\fgenerated_at\x18\x05 \x01(\x03R\vgeneratedAt\x12\"\n" +
	"\x04info\x18\x06 \x01(\v2\x0e.plot.PlotInfoR\x04info2S\n" +
	"\x0fMassListService\x12@\n" +
	"\x0fProcessMassList\x12\x15.plot.MassListRequest\x1a\x16.plot.MassListResponseB\x18Z\x16src/protobuf/plot;plotb\x06proto3"

var (
	file_src_protobuf_plot_proto_rawDescOnce sync.Once
	file_src_protobuf_plot_proto_rawDescData []byte
)

func file_src_protobuf_plot_proto_rawDescGZIP() []byte {
	file_src_protobuf_plot_proto_rawDescOnce.Do(func() {
		file_src_protobuf_plot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_src_protobuf_plot_proto_rawDesc), len(file_src_protobuf_plot_proto_rawDesc)))
	})
	return file_src_protobuf_plot_proto_rawDescData
}

var file_src_protobuf_plot_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_src_protobuf_plot_proto_goTypes = []any{
	(*PlotInfo)(nil),         // 0: plot.PlotInfo
	(*BruttoRange)(nil),      // 1: plot.BruttoRange
	(*MassListRequest)(nil),  // 2: plot.MassListRequest
	(*MassListResponse)(nil), // 3: plot.MassListResponse
	nil,                      // 4: plot.MassListRequest.BruttoDictEntry
	nil,                      // 5: plot.MassListRequest.OptionsEntry
}
var file_src_protobuf_plot_proto_depIdxs = []int32{
	4, // 0: plot.MassListRequest.brutto_dict:type_name -> plot.MassListRequest.BruttoDictEntry
	5, // 1: plot.MassListRequest.options:type_name -> plot.MassListRequest.OptionsEntry
	0, // 2: plot.MassListResponse.info:type_name -> plot.PlotInfo
	1, // 3: plot.MassListRequest.BruttoDictEntry.value:type_name -> plot.BruttoRange
	2, // 4: plot.MassListService.ProcessMassList:input_type -> plot.MassListRequest
	3, // 5: plot.MassListService.ProcessMassList:output_type -> plot.MassListResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_src_protobuf_plot_proto_init() }
func file_src_protobuf_plot_proto_init() {
	if File_src_protobuf_plot_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_src_protobuf_plot_proto_rawDesc), len(file_src_protobuf_plot_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_src_protobuf_plot_proto_goTypes,
		DependencyIndexes: file_src_protobuf_plot_proto_depIdxs,
		MessageInfos:      file_src_protobuf_plot_proto_msgTypes,
	}.Build()
	File_src_protobuf_plot_proto = out.File
	file_src_protobuf_plot_proto_goTypes = nil
	file_src_protobuf_plot_proto_depIdxs = nil
}
