# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from src.protobuf import plot_pb2 as src_dot_protobuf_dot_plot__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in src/protobuf/plot_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TextServiceStub:
    """Сервис с методами
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessText = channel.unary_unary(
                '/textservice.TextService/ProcessText',
                request_serializer=src_dot_protobuf_dot_plot__pb2.TextRequest.SerializeToString,
                response_deserializer=src_dot_protobuf_dot_plot__pb2.TextResponse.FromString,
                _registered_method=True)
        self.StreamProcessText = channel.unary_stream(
                '/textservice.TextService/StreamProcessText',
                request_serializer=src_dot_protobuf_dot_plot__pb2.TextRequest.SerializeToString,
                response_deserializer=src_dot_protobuf_dot_plot__pb2.TextChunk.FromString,
                _registered_method=True)
        self.AnalyzeTextStream = channel.stream_unary(
                '/textservice.TextService/AnalyzeTextStream',
                request_serializer=src_dot_protobuf_dot_plot__pb2.TextChunk.SerializeToString,
                response_deserializer=src_dot_protobuf_dot_plot__pb2.TextAnalysis.FromString,
                _registered_method=True)
        self.ChatStream = channel.stream_stream(
                '/textservice.TextService/ChatStream',
                request_serializer=src_dot_protobuf_dot_plot__pb2.ChatMessage.SerializeToString,
                response_deserializer=src_dot_protobuf_dot_plot__pb2.ChatMessage.FromString,
                _registered_method=True)


class TextServiceServicer:
    """Сервис с методами
    """

    def ProcessText(self, request, context):
        """Обычный RPC (запрос-ответ)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamProcessText(self, request, context):
        """Server Streaming (сервер отправляет несколько сообщений)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyzeTextStream(self, request_iterator, context):
        """Client Streaming (клиент отправляет несколько сообщений)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChatStream(self, request_iterator, context):
        """Bidirectional Streaming (оба направления)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TextServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessText': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessText,
                    request_deserializer=src_dot_protobuf_dot_plot__pb2.TextRequest.FromString,
                    response_serializer=src_dot_protobuf_dot_plot__pb2.TextResponse.SerializeToString,
            ),
            'StreamProcessText': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamProcessText,
                    request_deserializer=src_dot_protobuf_dot_plot__pb2.TextRequest.FromString,
                    response_serializer=src_dot_protobuf_dot_plot__pb2.TextChunk.SerializeToString,
            ),
            'AnalyzeTextStream': grpc.stream_unary_rpc_method_handler(
                    servicer.AnalyzeTextStream,
                    request_deserializer=src_dot_protobuf_dot_plot__pb2.TextChunk.FromString,
                    response_serializer=src_dot_protobuf_dot_plot__pb2.TextAnalysis.SerializeToString,
            ),
            'ChatStream': grpc.stream_stream_rpc_method_handler(
                    servicer.ChatStream,
                    request_deserializer=src_dot_protobuf_dot_plot__pb2.ChatMessage.FromString,
                    response_serializer=src_dot_protobuf_dot_plot__pb2.ChatMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'textservice.TextService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('textservice.TextService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TextService:
    """Сервис с методами
    """

    @staticmethod
    def ProcessText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/textservice.TextService/ProcessText',
            src_dot_protobuf_dot_plot__pb2.TextRequest.SerializeToString,
            src_dot_protobuf_dot_plot__pb2.TextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamProcessText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/textservice.TextService/StreamProcessText',
            src_dot_protobuf_dot_plot__pb2.TextRequest.SerializeToString,
            src_dot_protobuf_dot_plot__pb2.TextChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnalyzeTextStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/textservice.TextService/AnalyzeTextStream',
            src_dot_protobuf_dot_plot__pb2.TextChunk.SerializeToString,
            src_dot_protobuf_dot_plot__pb2.TextAnalysis.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChatStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/textservice.TextService/ChatStream',
            src_dot_protobuf_dot_plot__pb2.ChatMessage.SerializeToString,
            src_dot_protobuf_dot_plot__pb2.ChatMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
