# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: src/protobuf/plot.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'src/protobuf/plot.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17src/protobuf/plot.proto\x12\x04plot\"E\n\x08PlotInfo\x12\r\n\x05title\x18\x01 \x01(\t\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\x12\x0b\n\x03\x64pi\x18\x04 \x01(\x05\"\'\n\x0b\x42ruttoRange\x12\x0b\n\x03min\x18\x01 \x01(\x05\x12\x0b\n\x03max\x18\x02 \x01(\x05\"\xcb\x03\n\x0fMassListRequest\x12\x14\n\x0cspectra_name\x18\x01 \x01(\t\x12\x16\n\x0elow_percentile\x18\x02 \x01(\x02\x12\x17\n\x0fhigh_percentile\x18\x03 \x01(\x02\x12\x11\n\trel_error\x18\x04 \x01(\x02\x12\x12\n\ncharge_max\x18\x05 \x01(\x05\x12:\n\x0b\x62rutto_dict\x18\x06 \x03(\x0b\x32%.plot.MassListRequest.BruttoDictEntry\x12\x11\n\tprotocole\x18\x07 \x01(\t\x12\x14\n\x0cspectra_path\x18\x08 \x01(\t\x12\r\n\x05width\x18\t \x01(\x05\x12\x0e\n\x06height\x18\n \x01(\x05\x12\x0b\n\x03\x64pi\x18\x0b \x01(\x05\x12\x0e\n\x06\x66ormat\x18\x0c \x01(\t\x12\x33\n\x07options\x18\r \x03(\x0b\x32\".plot.MassListRequest.OptionsEntry\x1a\x44\n\x0f\x42ruttoDictEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12 \n\x05value\x18\x02 \x01(\x0b\x32\x11.plot.BruttoRange:\x02\x38\x01\x1a.\n\x0cOptionsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x91\x01\n\x10MassListResponse\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\x12\x0e\n\x06\x66ormat\x18\x02 \x01(\t\x12\x12\n\nsize_bytes\x18\x03 \x01(\x03\x12\x11\n\tmime_type\x18\x04 \x01(\t\x12\x14\n\x0cgenerated_at\x18\x05 \x01(\x03\x12\x1c\n\x04info\x18\x06 \x01(\x0b\x32\x0e.plot.PlotInfo2S\n\x0fMassListService\x12@\n\x0fProcessMassList\x12\x15.plot.MassListRequest\x1a\x16.plot.MassListResponseB\x18Z\x16src/protobuf/plot;plotb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.protobuf.plot_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\026src/protobuf/plot;plot'
  _globals['_MASSLISTREQUEST_BRUTTODICTENTRY']._loaded_options = None
  _globals['_MASSLISTREQUEST_BRUTTODICTENTRY']._serialized_options = b'8\001'
  _globals['_MASSLISTREQUEST_OPTIONSENTRY']._loaded_options = None
  _globals['_MASSLISTREQUEST_OPTIONSENTRY']._serialized_options = b'8\001'
  _globals['_PLOTINFO']._serialized_start=33
  _globals['_PLOTINFO']._serialized_end=102
  _globals['_BRUTTORANGE']._serialized_start=104
  _globals['_BRUTTORANGE']._serialized_end=143
  _globals['_MASSLISTREQUEST']._serialized_start=146
  _globals['_MASSLISTREQUEST']._serialized_end=605
  _globals['_MASSLISTREQUEST_BRUTTODICTENTRY']._serialized_start=489
  _globals['_MASSLISTREQUEST_BRUTTODICTENTRY']._serialized_end=557
  _globals['_MASSLISTREQUEST_OPTIONSENTRY']._serialized_start=559
  _globals['_MASSLISTREQUEST_OPTIONSENTRY']._serialized_end=605
  _globals['_MASSLISTRESPONSE']._serialized_start=608
  _globals['_MASSLISTRESPONSE']._serialized_end=753
  _globals['_MASSLISTSERVICE']._serialized_start=755
  _globals['_MASSLISTSERVICE']._serialized_end=838
# @@protoc_insertion_point(module_scope)
