// text_service.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: src/protobuf/plot.proto

package plot

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MassListService_ProcessMassList_FullMethodName = "/plot.MassListService/ProcessMassList"
)

// MassListServiceClient is the client API for MassListService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MassListServiceClient interface {
	ProcessMassList(ctx context.Context, in *MassListRequest, opts ...grpc.CallOption) (*MassListResponse, error)
}

type massListServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMassListServiceClient(cc grpc.ClientConnInterface) MassListServiceClient {
	return &massListServiceClient{cc}
}

func (c *massListServiceClient) ProcessMassList(ctx context.Context, in *MassListRequest, opts ...grpc.CallOption) (*MassListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MassListResponse)
	err := c.cc.Invoke(ctx, MassListService_ProcessMassList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MassListServiceServer is the server API for MassListService service.
// All implementations must embed UnimplementedMassListServiceServer
// for forward compatibility.
type MassListServiceServer interface {
	ProcessMassList(context.Context, *MassListRequest) (*MassListResponse, error)
	mustEmbedUnimplementedMassListServiceServer()
}

// UnimplementedMassListServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMassListServiceServer struct{}

func (UnimplementedMassListServiceServer) ProcessMassList(context.Context, *MassListRequest) (*MassListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProcessMassList not implemented")
}
func (UnimplementedMassListServiceServer) mustEmbedUnimplementedMassListServiceServer() {}
func (UnimplementedMassListServiceServer) testEmbeddedByValue()                         {}

// UnsafeMassListServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MassListServiceServer will
// result in compilation errors.
type UnsafeMassListServiceServer interface {
	mustEmbedUnimplementedMassListServiceServer()
}

func RegisterMassListServiceServer(s grpc.ServiceRegistrar, srv MassListServiceServer) {
	// If the following call panics, it indicates UnimplementedMassListServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MassListService_ServiceDesc, srv)
}

func _MassListService_ProcessMassList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MassListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MassListServiceServer).ProcessMassList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MassListService_ProcessMassList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MassListServiceServer).ProcessMassList(ctx, req.(*MassListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MassListService_ServiceDesc is the grpc.ServiceDesc for MassListService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MassListService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "plot.MassListService",
	HandlerType: (*MassListServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessMassList",
			Handler:    _MassListService_ProcessMassList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "src/protobuf/plot.proto",
}
