# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: src/protobuf/plot.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'src/protobuf/plot.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17src/protobuf/plot.proto\x12\x0btextservice\"N\n\x0bTextRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x10\n\x08language\x18\x02 \x01(\t\x12\x11\n\tuppercase\x18\x03 \x01(\x08\x12\x0c\n\x04tags\x18\x04 \x03(\t\"\xcb\x01\n\x0cTextResponse\x12\x15\n\roriginal_text\x18\x01 \x01(\t\x12\x16\n\x0eprocessed_text\x18\x02 \x01(\t\x12\x0e\n\x06length\x18\x03 \x01(\x05\x12\x10\n\x08language\x18\x04 \x01(\t\x12\x39\n\x08metadata\x18\x05 \x03(\x0b\x32\'.textservice.TextResponse.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"C\n\tTextChunk\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\x12\x14\n\x0c\x63hunk_number\x18\x02 \x01(\x05\x12\x0f\n\x07is_last\x18\x03 \x01(\x08\"\xca\x01\n\x0cTextAnalysis\x12\x12\n\nword_count\x18\x01 \x01(\x05\x12\x12\n\nchar_count\x18\x02 \x01(\x05\x12\x16\n\x0esentence_count\x18\x03 \x01(\x05\x12\x44\n\x0eword_frequency\x18\x04 \x03(\x0b\x32,.textservice.TextAnalysis.WordFrequencyEntry\x1a\x34\n\x12WordFrequencyEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\"B\n\x0b\x43hatMessage\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x32\xaa\x02\n\x0bTextService\x12\x42\n\x0bProcessText\x12\x18.textservice.TextRequest\x1a\x19.textservice.TextResponse\x12G\n\x11StreamProcessText\x12\x18.textservice.TextRequest\x1a\x16.textservice.TextChunk0\x01\x12H\n\x11\x41nalyzeTextStream\x12\x16.textservice.TextChunk\x1a\x19.textservice.TextAnalysis(\x01\x12\x44\n\nChatStream\x12\x18.textservice.ChatMessage\x1a\x18.textservice.ChatMessage(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.protobuf.plot_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TEXTRESPONSE_METADATAENTRY']._loaded_options = None
  _globals['_TEXTRESPONSE_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_TEXTANALYSIS_WORDFREQUENCYENTRY']._loaded_options = None
  _globals['_TEXTANALYSIS_WORDFREQUENCYENTRY']._serialized_options = b'8\001'
  _globals['_TEXTREQUEST']._serialized_start=40
  _globals['_TEXTREQUEST']._serialized_end=118
  _globals['_TEXTRESPONSE']._serialized_start=121
  _globals['_TEXTRESPONSE']._serialized_end=324
  _globals['_TEXTRESPONSE_METADATAENTRY']._serialized_start=277
  _globals['_TEXTRESPONSE_METADATAENTRY']._serialized_end=324
  _globals['_TEXTCHUNK']._serialized_start=326
  _globals['_TEXTCHUNK']._serialized_end=393
  _globals['_TEXTANALYSIS']._serialized_start=396
  _globals['_TEXTANALYSIS']._serialized_end=598
  _globals['_TEXTANALYSIS_WORDFREQUENCYENTRY']._serialized_start=546
  _globals['_TEXTANALYSIS_WORDFREQUENCYENTRY']._serialized_end=598
  _globals['_CHATMESSAGE']._serialized_start=600
  _globals['_CHATMESSAGE']._serialized_end=666
  _globals['_TEXTSERVICE']._serialized_start=669
  _globals['_TEXTSERVICE']._serialized_end=967
# @@protoc_insertion_point(module_scope)
