// text_service.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: src/protobuf/plot.proto

package plot

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TextService_ProcessText_FullMethodName = "/plot.TextService/ProcessText"
)

// TextServiceClient is the client API for TextService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Сервис с методами
type TextServiceClient interface {
	// Обычный RPC (запрос-ответ)
	ProcessText(ctx context.Context, in *TextRequest, opts ...grpc.CallOption) (*TextResponse, error)
}

type textServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTextServiceClient(cc grpc.ClientConnInterface) TextServiceClient {
	return &textServiceClient{cc}
}

func (c *textServiceClient) ProcessText(ctx context.Context, in *TextRequest, opts ...grpc.CallOption) (*TextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TextResponse)
	err := c.cc.Invoke(ctx, TextService_ProcessText_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TextServiceServer is the server API for TextService service.
// All implementations must embed UnimplementedTextServiceServer
// for forward compatibility.
//
// Сервис с методами
type TextServiceServer interface {
	// Обычный RPC (запрос-ответ)
	ProcessText(context.Context, *TextRequest) (*TextResponse, error)
	mustEmbedUnimplementedTextServiceServer()
}

// UnimplementedTextServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTextServiceServer struct{}

func (UnimplementedTextServiceServer) ProcessText(context.Context, *TextRequest) (*TextResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProcessText not implemented")
}
func (UnimplementedTextServiceServer) mustEmbedUnimplementedTextServiceServer() {}
func (UnimplementedTextServiceServer) testEmbeddedByValue()                     {}

// UnsafeTextServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TextServiceServer will
// result in compilation errors.
type UnsafeTextServiceServer interface {
	mustEmbedUnimplementedTextServiceServer()
}

func RegisterTextServiceServer(s grpc.ServiceRegistrar, srv TextServiceServer) {
	// If the following call panics, it indicates UnimplementedTextServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TextService_ServiceDesc, srv)
}

func _TextService_ProcessText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TextServiceServer).ProcessText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TextService_ProcessText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TextServiceServer).ProcessText(ctx, req.(*TextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TextService_ServiceDesc is the grpc.ServiceDesc for TextService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TextService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "plot.TextService",
	HandlerType: (*TextServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessText",
			Handler:    _TextService_ProcessText_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "src/protobuf/plot.proto",
}

const (
	PlotService_GeneratePlot_FullMethodName          = "/plot.PlotService/GeneratePlot"
	PlotService_StreamPlot_FullMethodName            = "/plot.PlotService/StreamPlot"
	PlotService_GenerateMultiplePlots_FullMethodName = "/plot.PlotService/GenerateMultiplePlots"
)

// PlotServiceClient is the client API for PlotService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PlotServiceClient interface {
	// Обычный RPC для получения графика
	GeneratePlot(ctx context.Context, in *PlotRequest, opts ...grpc.CallOption) (*PlotResponse, error)
	// Стриминг для больших графиков
	StreamPlot(ctx context.Context, in *PlotRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PlotChunk], error)
	// Множество графиков
	GenerateMultiplePlots(ctx context.Context, in *MultiPlotRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PlotResponse], error)
}

type plotServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPlotServiceClient(cc grpc.ClientConnInterface) PlotServiceClient {
	return &plotServiceClient{cc}
}

func (c *plotServiceClient) GeneratePlot(ctx context.Context, in *PlotRequest, opts ...grpc.CallOption) (*PlotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlotResponse)
	err := c.cc.Invoke(ctx, PlotService_GeneratePlot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plotServiceClient) StreamPlot(ctx context.Context, in *PlotRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PlotChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PlotService_ServiceDesc.Streams[0], PlotService_StreamPlot_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PlotRequest, PlotChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PlotService_StreamPlotClient = grpc.ServerStreamingClient[PlotChunk]

func (c *plotServiceClient) GenerateMultiplePlots(ctx context.Context, in *MultiPlotRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PlotResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PlotService_ServiceDesc.Streams[1], PlotService_GenerateMultiplePlots_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[MultiPlotRequest, PlotResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PlotService_GenerateMultiplePlotsClient = grpc.ServerStreamingClient[PlotResponse]

// PlotServiceServer is the server API for PlotService service.
// All implementations must embed UnimplementedPlotServiceServer
// for forward compatibility.
type PlotServiceServer interface {
	// Обычный RPC для получения графика
	GeneratePlot(context.Context, *PlotRequest) (*PlotResponse, error)
	// Стриминг для больших графиков
	StreamPlot(*PlotRequest, grpc.ServerStreamingServer[PlotChunk]) error
	// Множество графиков
	GenerateMultiplePlots(*MultiPlotRequest, grpc.ServerStreamingServer[PlotResponse]) error
	mustEmbedUnimplementedPlotServiceServer()
}

// UnimplementedPlotServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPlotServiceServer struct{}

func (UnimplementedPlotServiceServer) GeneratePlot(context.Context, *PlotRequest) (*PlotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GeneratePlot not implemented")
}
func (UnimplementedPlotServiceServer) StreamPlot(*PlotRequest, grpc.ServerStreamingServer[PlotChunk]) error {
	return status.Error(codes.Unimplemented, "method StreamPlot not implemented")
}
func (UnimplementedPlotServiceServer) GenerateMultiplePlots(*MultiPlotRequest, grpc.ServerStreamingServer[PlotResponse]) error {
	return status.Error(codes.Unimplemented, "method GenerateMultiplePlots not implemented")
}
func (UnimplementedPlotServiceServer) mustEmbedUnimplementedPlotServiceServer() {}
func (UnimplementedPlotServiceServer) testEmbeddedByValue()                     {}

// UnsafePlotServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PlotServiceServer will
// result in compilation errors.
type UnsafePlotServiceServer interface {
	mustEmbedUnimplementedPlotServiceServer()
}

func RegisterPlotServiceServer(s grpc.ServiceRegistrar, srv PlotServiceServer) {
	// If the following call panics, it indicates UnimplementedPlotServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PlotService_ServiceDesc, srv)
}

func _PlotService_GeneratePlot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlotServiceServer).GeneratePlot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlotService_GeneratePlot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlotServiceServer).GeneratePlot(ctx, req.(*PlotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlotService_StreamPlot_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PlotRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PlotServiceServer).StreamPlot(m, &grpc.GenericServerStream[PlotRequest, PlotChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PlotService_StreamPlotServer = grpc.ServerStreamingServer[PlotChunk]

func _PlotService_GenerateMultiplePlots_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(MultiPlotRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PlotServiceServer).GenerateMultiplePlots(m, &grpc.GenericServerStream[MultiPlotRequest, PlotResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PlotService_GenerateMultiplePlotsServer = grpc.ServerStreamingServer[PlotResponse]

// PlotService_ServiceDesc is the grpc.ServiceDesc for PlotService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PlotService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "plot.PlotService",
	HandlerType: (*PlotServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GeneratePlot",
			Handler:    _PlotService_GeneratePlot_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamPlot",
			Handler:       _PlotService_StreamPlot_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GenerateMultiplePlots",
			Handler:       _PlotService_GenerateMultiplePlots_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "src/protobuf/plot.proto",
}

const (
	MassListService_ProcessMassList_FullMethodName = "/plot.MassListService/ProcessMassList"
)

// MassListServiceClient is the client API for MassListService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MassListServiceClient interface {
	ProcessMassList(ctx context.Context, in *MassListRequest, opts ...grpc.CallOption) (*MassListResponse, error)
}

type massListServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMassListServiceClient(cc grpc.ClientConnInterface) MassListServiceClient {
	return &massListServiceClient{cc}
}

func (c *massListServiceClient) ProcessMassList(ctx context.Context, in *MassListRequest, opts ...grpc.CallOption) (*MassListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MassListResponse)
	err := c.cc.Invoke(ctx, MassListService_ProcessMassList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MassListServiceServer is the server API for MassListService service.
// All implementations must embed UnimplementedMassListServiceServer
// for forward compatibility.
type MassListServiceServer interface {
	ProcessMassList(context.Context, *MassListRequest) (*MassListResponse, error)
	mustEmbedUnimplementedMassListServiceServer()
}

// UnimplementedMassListServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMassListServiceServer struct{}

func (UnimplementedMassListServiceServer) ProcessMassList(context.Context, *MassListRequest) (*MassListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProcessMassList not implemented")
}
func (UnimplementedMassListServiceServer) mustEmbedUnimplementedMassListServiceServer() {}
func (UnimplementedMassListServiceServer) testEmbeddedByValue()                         {}

// UnsafeMassListServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MassListServiceServer will
// result in compilation errors.
type UnsafeMassListServiceServer interface {
	mustEmbedUnimplementedMassListServiceServer()
}

func RegisterMassListServiceServer(s grpc.ServiceRegistrar, srv MassListServiceServer) {
	// If the following call panics, it indicates UnimplementedMassListServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MassListService_ServiceDesc, srv)
}

func _MassListService_ProcessMassList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MassListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MassListServiceServer).ProcessMassList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MassListService_ProcessMassList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MassListServiceServer).ProcessMassList(ctx, req.(*MassListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MassListService_ServiceDesc is the grpc.ServiceDesc for MassListService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MassListService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "plot.MassListService",
	HandlerType: (*MassListServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessMassList",
			Handler:    _MassListService_ProcessMassList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "src/protobuf/plot.proto",
}
